### PR TITLE
Add ICON (ICX) Token

### PR DESCRIPTION
**Pull request by ghost**
Please add the ICON token

### CODE REVIEW

**Comment by zackcoburn** [comment]
I assume this token is https://icon.foundation/en/?

Is the token address listed on that page somewhere, for verification?

Can you verify the token code on Etherscan? https://etherscan.io/verifyContract?a=0xb5A5F22694352C15B00323844aD545ABb2B11028

Also, is the intention really for there to be 0 decimals? These numbers look quite large: https://etherscan.io/token/0xb5A5F22694352C15B00323844aD545ABb2B11028

**Comment by dc75la** [comment]
Yes that is correct.

I've just received it via Telegram;
[image: Inline afbeelding 1]

The code verification ? I need a bit of help to check that.

No it has 18 decimals :) I hoped to be trillionair already but no... had to
divide by 18 LOL



2017-09-20 16:18 GMT+02:00 Zack Coburn <notifications@github.com>:

**Comment by zackcoburn** [comment]
I suspect there are some problems with the token code, in particular excluding the "decimals" function, but I'll need the code to be verified to know for sure what's going on.

**Comment by zackcoburn** [comment]
Also, I can't see your image. But I really need the team to list the token address on their Web page for verification. Or I need a team member to send me an email confirming the token address. But also, they really need to verify the code and figure out their decimals function.

**Comment by dc75la** [comment]
Ok, I understand how it works now. Sorry to be so impatient. I will wait
for that.

2017-09-20 17:08 GMT+02:00 Zack Coburn <notifications@github.com>:

**Comment by dc75la** [comment]
The code is verified btw;
https://etherscan.io/address/0xb5a5f22694352c15b00323844ad545abb2b11028#code

more information about the token and how to add to mew;
https://medium.com/helloiconworld/how-to-add-icx-custom-token-df944450f998

**Pull request closed without merging**
