### PR TITLE
Added Agrello DELTA (DLT) token to the repository

### PR DESCRIPTION
**Pull request by Lab5-Switzerland**
DELTA is being distributed right now and will hit exchanges soon. So far it looks it will only be traded in China, so EtherDelta will easily be the first exchange in the english speaking realm to trade DELTA (DLT).
On behalf of the community i would like to kindly and humbly ask to add this commit as soon as posslible.
Thanks alot, Zack :)

Cheers n best wishes !
Lab5 - Dennis Riegelsberger
http://lab5.ch ( <- yes, shamelessly shilling myself there :D )

### CODE REVIEW

**Comment by zackcoburn** [comment]
Is this token address verified somewhere on your Web site? I can't find it. (I need this as verification.)

**Comment by Lab5-Switzerland** [comment]
The producer's website is agrello.org.
their continuous info outlet is on the subgomain, the blog : http://blog.agrello.org .
HERE is the article that explains users how to show DTL in MyEtherWallet; In that article, you can see and verify the adress of the contract:

https://blog.agrello.org/how-to-withdraw-your-delta-c796770b5584

cheers :)

**Comment by Lab5-Switzerland** [comment]
If you still need more info, pls tell me . Agrello is the producer of the DELTA ( DLT ) token. 
Verification is in the middle of their article : https://blog.agrello.org/how-to-withdraw-your-delta-c796770b5584

**Comment by zackcoburn** [comment]
Added, thanks!

**Pull request closed without merging**
