### PR TITLE
Add Arexium (ARX) token.

### PR DESCRIPTION
**Pull request by jaaneh**
I would like to add Arexium to etherdelta.

Address: 0xe256bb0b2a3457e54db3a41cf5a8b826aca222a8
Token symbol: ARX
Decimals: 18

Website: https://www.arexium.io/
Twitter: https://twitter.com/arexium_io
Contract Source: https://etherscan.io/address/0xe256bb0b2a3457e54db3a41cf5a8b826aca222a8#code

Verification: https://www.arexium.io/v/

### CODE REVIEW

**Comment by jaaneh** [comment]
Hey, wondering if it's possible to add this token?

**Comment by zackcoburn** [comment]
Once it's more than just a coming soon page, yes.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by jaaneh** [comment]
@zackcoburn Cheers. We're working on the site, will be up soon.

**Comment by zackcoburn** [comment]
Perfect!

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Pull request closed without merging**
